[package]
name = "blockchain"
version = "0.1.0"
authors = ["bhargav55 <kacharlabhargav21@gmail.com>"]

[dependencies]
time = "0.1.38"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.7.0"